// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJwHHFZ3aeGpuGhX2NBpsTwishZ4j9WrA',
    appId: '1:388959458855:web:d4ebc09770d60b17b1e002',
    messagingSenderId: '388959458855',
    projectId: 'campusgoo-a0973',
    authDomain: 'campusgoo-a0973.firebaseapp.com',
    storageBucket: 'campusgoo-a0973.appspot.com',
    measurementId: 'G-ZZD8NWPQQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCuYEJ5DKCjqQpnQXozXhFiQ-urnGxRmo',
    appId: '1:388959458855:android:6be4fa0984bfc31bb1e002',
    messagingSenderId: '388959458855',
    projectId: 'campusgoo-a0973',
    storageBucket: 'campusgoo-a0973.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWMpmhhXvAP_1ebrudakhcT59xDgMFjm0',
    appId: '1:388959458855:ios:4622af7e9934ba41b1e002',
    messagingSenderId: '388959458855',
    projectId: 'campusgoo-a0973',
    storageBucket: 'campusgoo-a0973.appspot.com',
    iosBundleId: 'com.example.campusgoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWMpmhhXvAP_1ebrudakhcT59xDgMFjm0',
    appId: '1:388959458855:ios:946cdeb64267b796b1e002',
    messagingSenderId: '388959458855',
    projectId: 'campusgoo-a0973',
    storageBucket: 'campusgoo-a0973.appspot.com',
    iosBundleId: 'com.example.campusgoo.RunnerTests',
  );
}
